name: "Insert Stoic Quote"
description: "Insert a Stoic quote and interpretation into a markdown file using kathekon"
author: "Jan Müller"

inputs:
  file:
    description: "The file to update (e.g. README.md)"
    required: false
    default: "README.md"
  method:
    description: "Method to use for interpretation: db, gpt, gpt+fallback, db+fixed"
    required: false
    default: "db+fixed"
  author:
    description: "Filter quotes by Stoic author (e.g. Seneca, Marcus Aurelius)"
    required: false
    default: ""
  type:
    description: "Quote type: daily or random"
    required: false
    default: "daily"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install kathekon
      run: |
        pip install --upgrade pip
        pip install kathekon
      shell: bash

    - name: Insert quote into file
      run: |
        if [ "${{ inputs.type }}" = "random" ]; then
          kathekon readme random --file "${{ inputs.file }}" --author "${{ inputs.author }}" --method "${{ inputs.method }}"
        else
          kathekon readme daily --file "${{ inputs.file }}" --author "${{ inputs.author }}" --method "${{ inputs.method }}"
        fi
      shell: bash

    - name: Configure Git
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      shell: bash

    - name: Commit and Push changes
      run: |
        git add "${{ inputs.file }}"
        git commit -m "Insert Stoic quote via GitHub Action" || echo "Nothing to commit"
        git push
      shell: bash

