name: 'Insert Stoic Quote'
description: 'Insert a Stoic quote into a markdown file using kathekon.'
author: 'janthmueller'
branding:
  icon: 'book'
  color: 'blue'

inputs:
  file:
    description: 'File to insert the quote into'
    required: false
    default: 'README.md'

  type:
    description: 'Type of quote: daily or random'
    required: false
    default: 'daily'

  method:
    description: 'Interpretation method: db, gpt, db+fixed, gpt+fallback'
    required: false

  author:
    description: 'Optional author filter (e.g., Marcus Aurelius)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install kathekon
      run: |
        pip install --upgrade pip
        pip install kathekon
      shell: bash

    - name: Insert Stoic Quote
      run: |
        method="${{ inputs.method }}"
        type="${{ inputs.type }}"
        file="${{ inputs.file }}"
        author="${{ inputs.author }}"

        if [ "$type" = "daily" ]; then
          method="${method:-db+fixed}"
          cmd="kathekon readme daily --file \"$file\" --method \"$method\""
        else
          method="${method:-db}"
          cmd="kathekon readme random --file \"$file\" --method \"$method\""
          if [ -n "$author" ]; then
            cmd="$cmd --author \"$author\""
          fi
        fi

        eval "$cmd"
      shell: bash

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add "${{ inputs.file }}"
        git commit -m "Insert Stoic quote ($(date +'%Y-%m-%d'))" || echo "Nothing to commit"
        git push
      shell: bash

